### ISSUE TITLE
divide-smtyp-data

### ISSUE THREAD

**Issue by johannesocean** [sharksmhi/odv_transformer#1]
Divide BTL-, CTD- and TUBE-data to different blocks.

Data are catagorized to to the sampling type which it has been measured with eg. CTD, bottle, tube sampling. Hence, each row in the data table must only be labeled with one "SMTYP".

**Comment by johannesocean** [comment]
@LenaSMHI hur sa vi att uppdelningen av BTL,CTD parametrar skulle göras?

Alternativ:
- Behålla parameternamnen TEMP_BTL, TEMP_CTD och sedan ha värdena på olika rader (baserat på sample type)?
- Ha en parameter "TEMP" och sedan ha värdena på olika rader (baserat på sample type)?
- Olika filer?

**Comment by LenaSMHI** [comment]
@JohannesSMHI alternativet i mitten:

- Ha en parameter "TEMP" och sedan ha värdena på olika rader (baserat på sample type)?
